In [129]:
import pandas as pd
import numpy as np

In [130]:
df=pd.read_csv('IMDB Dataset.csv')

In [131]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Text Preprocessing

In [132]:
df.shape

(50000, 2)

In [133]:
df.describe()

                                                   Review Sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [134]:
#check null values
df.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [135]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing Quotes

In [136]:
# This removes: , (comma), ' (single quote), and " (double quote)
df['Review'] = df['Review'].str.replace(r"[ ().'\" ]", " ", regex=True)

# Removing HTML Tags

In [137]:
# 1. Remove all HTML tags (the non-greedy way)
df['Review'] = df['Review'].str.replace(r"<.*?>", " ", regex=True)

In [138]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production    The filming t...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there s a family where a little boy ...  negative
4      Petter Mattei s  Love in the Time of Money  is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I m going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Lowercasing

In [139]:
df['Review']=df['Review'].str.lower()

In [140]:
df['Review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production    the filming t...
2        i thought this was a wonderful way to spend ti...
3        basically there s a family where a little boy ...
4        petter mattei s  love in the time of money  is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i m going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: Review, Length: 50000, dtype: object

# Remove Punctuation

In [141]:
df['Review'] = df['Review'].str.replace(r"a-zA-Z0-9"," ",regex=True)
df["Review"] = df["Review"].str.replace(r"\s+"," ",regex=True).str.strip()

In [142]:
df['Review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there s a family where a little boy ...
4        petter mattei s love in the time of money is a...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i m going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: Review, Length: 50000, dtype: object

# Remove Stop Words

In [143]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hpwor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [144]:
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in stop_words])

df['Review'] = df['Review'].apply(remove_stopwords)

In [145]:
df["Review"]

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically family little boy jake thinks zombie...
4        petter mattei love time money visually stunnin...
                               ...
49995    thought movie right good job creative original...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: Review, Length: 50000, dtype: object

# Tokenization

In [ ]:
from nltk.tokenize import word_tokenize