In [48]:
import pandas as pd
import numpy as np

In [49]:
df=pd.read_csv('IMDB Dataset.csv')

In [50]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Text Preprocessing

In [51]:
df.shape

(50000, 2)

In [52]:
df.describe()

                                                   Review Sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [53]:
#check null values
df.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [54]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing HTML Tags

In [55]:
# 1. Remove all HTML tags (the non-greedy way)
df['Review'] = df['Review'].str.replace(r"<.*?>", " ", regex=True)

In [56]:
df

                                                  Review Sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production.   The filming t...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing Quotes

In [57]:
# This removes: , (comma), ' (single quote), and " (double quote)
df['Review'] = df['Review'].str.replace(r"[ ().'\" ]", " ", regex=True)

# Lowercasing

In [58]:
df['Review']=df['Review'].str.lower()

In [59]:
df['Review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production    the filming t...
2        i thought this was a wonderful way to spend ti...
3        basically there s a family where a little boy ...
4        petter mattei s  love in the time of money  is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i m going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: Review, Length: 50000, dtype: object

# Remove Punctuation

In [60]:
df['Review'] = df['Review'].str.replace(r"[^a-zA-Z0-9]"," ",regex=True)
df["Review"] = df["Review"].str.replace(r"\s+"," ",regex=True).str.strip()

In [61]:
df['Review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there s a family where a little boy ...
4        petter mattei s love in the time of money is a...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    i m going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: Review, Length: 50000, dtype: object

# Tokenization

In [62]:
from nltk.tokenize import word_tokenize,sent_tokenize
def tokenize_clean(text):
    tokens=word_tokenize(text)
    return tokens
df['Review'] = df['Review'].apply(tokenize_clean)

# Remove Stop Words

In [66]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
# Keep negation words
negation_words = {'not', 'no', 'nor', 'never'}
stop_words = stop_words - negation_words

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hpwor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [67]:
def remove_stopwords(text):
    return " ".join(
        [word for word in text.split() if word.lower() not in stop_words]
    )

In [68]:
df["Review"]

0        [one, of, the, other, reviewers, has, mentione...
1        [a, wonderful, little, production, the, filmin...
2        [i, thought, this, was, a, wonderful, way, to,...
3        [basically, there, s, a, family, where, a, lit...
4        [petter, mattei, s, love, in, the, time, of, m...
                               ...
49995    [i, thought, this, movie, did, a, down, right,...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [i, am, a, catholic, taught, in, parochial, el...
49998    [i, m, going, to, have, to, disagree, with, th...
49999    [no, one, expects, the, star, trek, movies, to...
Name: Review, Length: 50000, dtype: object

# Lemmatization

In [69]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

True

In [70]:
lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(t, pos='v') for t in tokens]

df['Review'] = df['Review'].apply(lemmatize_tokens)

In [71]:
df

                                                  Review Sentiment
0      [one, of, the, other, reviewers, have, mention...  positive
1      [a, wonderful, little, production, the, film, ...  positive
2      [i, think, this, be, a, wonderful, way, to, sp...  positive
3      [basically, there, s, a, family, where, a, lit...  negative
4      [petter, mattei, s, love, in, the, time, of, m...  positive
...                                                  ...       ...
49995  [i, think, this, movie, do, a, down, right, go...  positive
49996  [bad, plot, bad, dialogue, bad, act, idiotic, ...  negative
49997  [i, be, a, catholic, teach, in, parochial, ele...  negative
49998  [i, m, go, to, have, to, disagree, with, the, ...  negative
49999  [no, one, expect, the, star, trek, movies, to,...  negative

[50000 rows x 2 columns]

In [72]:
df['Review'] = df['Review'].apply(lemmatize_tokens)

In [73]:
df

                                                  Review Sentiment
0      [one, of, the, other, reviewers, have, mention...  positive
1      [a, wonderful, little, production, the, film, ...  positive
2      [i, think, this, be, a, wonderful, way, to, sp...  positive
3      [basically, there, s, a, family, where, a, lit...  negative
4      [petter, mattei, s, love, in, the, time, of, m...  positive
...                                                  ...       ...
49995  [i, think, this, movie, do, a, down, right, go...  positive
49996  [bad, plot, bad, dialogue, bad, act, idiotic, ...  negative
49997  [i, be, a, catholic, teach, in, parochial, ele...  negative
49998  [i, m, go, to, have, to, disagree, with, the, ...  negative
49999  [no, one, expect, the, star, trek, movies, to,...  negative

[50000 rows x 2 columns]

In [74]:
df['Cleaned_Text'] = df['Review'].apply(lambda x: " ".join(x))

In [75]:
df

,Review,Sentiment,Cleaned_Text
0,"[one, of, the, other, reviewers, have, mention...",positive,one of the other reviewers have mention that a...
1,"[a, wonderful, little, production, the, film, ...",positive,a wonderful little production the film techniq...
2,"[i, think, this, be, a, wonderful, way, to, sp...",positive,i think this be a wonderful way to spend time ...
3,"[basically, there, s, a, family, where, a, lit...",negative,basically there s a family where a little boy ...
4,"[petter, mattei, s, love, in, the, time, of, m...",positive,petter mattei s love in the time of money be a...
...,...,...,...
49995,"[i, think, this, movie, do, a, down, right, go...",positive,i think this movie do a down right good job it...
49996,"[bad, plot, bad, dialogue, bad, act, idiotic, ...",negative,bad plot bad dialogue bad act idiotic direct t...
49997,"[i, be, a, catholic, teach, in, parochial, ele...",negative,i be a catholic teach in parochial elementary ...
49998,"[i, m, go, to, have, to, disagree, with, the, ...",negative,i m go to have to disagree with the previous c...
49999,"[no, one, expect, the, star, trek, movies, to,...",negative,no one expect the star trek movies to be high ...

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=5000)

In [77]:
X = vectorizer.fit_transform(df['Review'])
y= df['Sentiment']

AttributeError: 'list' object has no attribute 'lower'